version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://aequitas.apice.unibo.it:4005
