name: deploy
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Release
    concurrency:
      group: deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "aequitaseu/frontend"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history

      - name: Restore Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Compute Version
        run: echo "IMAGE_VERSION=$(jq -r .version package.json)-$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Login on DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG $IMAGE_TAG:$IMAGE_VERSION

      - name: Push Docker Image
        run: |
          docker push $IMAGE_TAG:$IMAGE_VERSION
          docker push $IMAGE_TAG:latest

      - name: Release on GitHub
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ASSET_NAME=$(basename $GITHUB_REPOSITORY)
          zip -r $ASSET_NAME out
          gh release create $IMAGE_VERSION $ASSET_NAME.zip --title "v$IMAGE_VERSION"
