name: deploy
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Release
    concurrency:
      group: deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "aequitaseu/frontend"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history
          token: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Restore Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login on DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker image creation
        run: docker build .

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: "aequitaseu/frontend"
        run: |
          npm install
          npx semantic-release
